security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_PLANER:         [ROLE_USER]
        ROLE_ASSEMBLY_ADMIN: [ROLE_PLANER]
        ROLE_ADMIN:          [ROLE_ASSEMBLY_ADMIN]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            login_throttling:
                max_attempts: 5
                interval: '15 minutes'

            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: dashboard

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
                path: /

            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                enable_csrf: true

            logout:
                path: security_logout
                target: security_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/password-reset, roles: PUBLIC_ACCESS }
        - { path: ^/kalender, roles: PUBLIC_ACCESS }
        - { path: ^/versammlung, roles: PUBLIC_ACCESS }
        - { path: ^/impressum, roles: PUBLIC_ACCESS }
        - { path: ^/datenschutz, roles: PUBLIC_ACCESS }
        - { path: ^/language, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
